version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:3
    restart: always
    # volumes:
    #   - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api
    build: .
    restart: always
    image: node-api
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    ports:
      - "5050:5050"
    links:
      - mongodb
